version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.7.0-alpha.1
    command: migrate -c /etc/config/kratos/kratos.yml sql -e --yes
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - postgresd
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v0.7.0-alpha.1
    ports:
      - '4433:4433'
      - '4434:4434'
    command: serve --config /etc/config/kratos/kratos.yml all
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - kratos-migrate
      - postgresd
      - zipkin
    links:
      - zipkin
    networks:
      - intranet

  service-ui:
    image: oryd/kratos-selfservice-ui-node:v0.7.0-alpha.1
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
    ports:
      - '4455:3000'
    networks:
      - intranet

  zipkin:
    ports:
      - '9411:9411'
    image: openzipkin/zipkin
    networks:
      - intranet

  postgresd:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

networks:
  intranet: {}
