security:
  jwtKey: 4125442A472D4B614E645267556B58703273357638792F423F4528482B4D6251
  cookieId: idtoken

  otp:
    duration: 120
    length: 6

features:
  api:
    enableGraphql: true
  auth:
    enabled: true
    enableJwt: true
    enableSession: true
    enableCookie: true
  enableSoftDelete: true

logging:
  sentry:
    dsn: https://dgfdfg56jy53673o7rkuyd@o439891.ingest.sentry.io/79898575
    environment: Staging

files:
  securityCert: dist/secrets/cert.pem
  securityKey: dist/secrets/key.pem
