import { Field, ObjectType } from '@nestjs/graphql';
import { ApiProperty } from '@nestjs/swagger';

/**
 * @description account response is a public representation of an account
 */
@ObjectType('BaseEntityType', {
  description: 'Base entity type',
  isAbstract: true,
})
export abstract class BaseEntityType {
  /**
   * @description ID field is a database generated unique identifier for an entity
   */
  @Field({
    description: 'ID field is a database generated unique identifier for an entity',
  })
  @ApiProperty({
    description: 'ID field is a database generated unique identifier for an entity',
  })
  id!: string;

  /**
   * @description The date this entity as created. This is autogenerated
   */
  @Field({
    description: 'The date this entity as created. This is autogenerated',
  })
  @ApiProperty({ description: 'The date this entity as created. This is autogenerated' })
  createdAt!: Date;

  /**
   * @description Last date this entity as updated. This is autogenerated
   */
  @Field({
    description: 'Last date this entity as updated. This is autogenerated',
  })
  @ApiProperty({ description: 'Last date this entity as updated. This is autogenerated' })
  updatedAt!: Date;
}
